### ISSUE TITLE
Close Socket properly

### ISSUE THREAD

**Issue by AdrKacz** [AdrKacz/super-duper-guacamole#48]
# Close Socket properly

## Error

```
...
Server is alive with 2 peers connected.
497e6b7e-2367-4f3c-af00-94c2bb7cd64f::Wxxix
Peer index 0 <<< Wxxix <<< 497e6b7e-2367-4f3c-af00-94c2bb7cd64f
Connection closed by Peer index 1
connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1013, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1088, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1143, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.ws_handler(self)
  File "/app/main.py", line 37, in chat
    await peer.send(f"{user}::{message}")
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 619, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
Server is alive with 1 peers connected.
...
```

L'erreur apparaît de temps en temps (observé dans les *logs* 1 fois)

**Comment by AdrKacz** [comment]
Not relevant anymore (one socket only)
